// Mock data for development and testing
export const mockUsers = [
  { id: "1", name: "Sarah Johnson", email: "sarah@example.com", role: "manager" },
  { id: "2", name: "Mike Chen", email: "mike@example.com", role: "member" },
  { id: "3", name: "Emily Davis", email: "emily@example.com", role: "member" },
  { id: "4", name: "John Doe", email: "john@example.com", role: "admin" },
  { id: "5", name: "Jane Smith", email: "jane@example.com", role: "member" },
];

export const mockProjects = [
  { id: "1", name: "E-commerce Platform", status: "in-progress" },
  { id: "2", name: "Mobile App Redesign", status: "in-progress" },
  { id: "3", name: "Data Analytics Dashboard", status: "completed" },
  { id: "4", name: "Marketing Website", status: "not-started" },
];

export const mockPrograms = [
  { id: "1", name: "Digital Transformation", status: "active" },
  { id: "2", name: "Product Innovation", status: "planning" },
  { id: "3", name: "Market Expansion", status: "active" },
];

export const mockBudgets = [
  {
    _id: "1",
    name: "Project Alpha Budget",
    amount: 50000,
    spent: 25000,
    category: "Development",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    status: "active",
  },
  {
    _id: "2",
    name: "Marketing Budget",
    amount: 20000,
    spent: 15000,
    category: "Marketing",
    startDate: "2024-01-01",
    endDate: "2024-06-30",
    status: "active",
  },
];

export const mockExpenses = [
  {
    _id: "1",
    description: "Software licenses",
    amount: 5000,
    category: "Software",
    date: "2024-01-15",
    budgetId: "1",
  },
  {
    _id: "2",
    description: "Marketing materials",
    amount: 3000,
    category: "Marketing",
    date: "2024-01-20",
    budgetId: "2",
  },
];

export const mockRisks = [
  {
    _id: "1",
    title: "Database performance issues",
    description: "Potential performance bottlenecks in database queries",
    probability: "medium",
    impact: "high",
    status: "open",
    category: "Technical",
    assignee: "Mike Chen",
    dueDate: "2024-02-15",
    mitigationPlan: "Optimize queries and add indexing",
  },
  {
    _id: "2",
    title: "Budget overrun risk",
    description: "Project may exceed allocated budget",
    probability: "low",
    impact: "medium",
    status: "mitigated",
    category: "Financial",
    assignee: "Sarah Johnson",
    dueDate: "2024-01-30",
    mitigationPlan: "Regular budget reviews and cost tracking",
  },
];

export const mockDocuments = [
  {
    _id: "1",
    title: "Project Requirements",
    description: "Detailed project requirements document",
    fileName: "requirements.pdf",
    fileSize: 2048576,
    fileType: "application/pdf",
    category: "Requirements",
    projectId: "1",
    uploadedBy: "John Doe",
    uploadedAt: "2024-01-15T10:30:00Z",
    lastModified: "2024-01-15T10:30:00Z",
    tags: ["requirements", "planning"],
    isPublic: true,
    downloadCount: 15,
  },
  {
    _id: "2",
    title: "Design Mockups",
    description: "UI/UX design mockups",
    fileName: "mockups.zip",
    fileSize: 10485760,
    fileType: "application/zip",
    category: "Design",
    projectId: "1",
    uploadedBy: "Jane Smith",
    uploadedAt: "2024-01-20T14:45:00Z",
    lastModified: "2024-01-20T14:45:00Z",
    tags: ["design", "ui", "ux"],
    isPublic: false,
    downloadCount: 8,
  },
];

export const mockTasks = [
  {
    _id: "1",
    title: "Update user authentication",
    description: "Implement new authentication system",
    status: "in-progress",
    priority: "high",
    assignee: "Mike Chen",
    reporter: "Sarah Johnson",
    project: "E-commerce Platform",
    startDate: "2024-01-10",
    dueDate: "2024-01-25",
    estimatedHours: 40,
    actualHours: 25,
    dependencies: "Database setup",
    tags: "authentication,security",
  },
  {
    _id: "2",
    title: "Design homepage layout",
    description: "Create responsive homepage design",
    status: "completed",
    priority: "medium",
    assignee: "Emily Davis",
    reporter: "Sarah Johnson",
    project: "Marketing Website",
    startDate: "2024-01-05",
    dueDate: "2024-01-15",
    estimatedHours: 20,
    actualHours: 18,
    dependencies: "",
    tags: "design,frontend",
  },
];

export const mockTeamMembers = [
  {
    _id: "1",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@example.com",
    phone: "+1-555-0101",
    role: "manager",
    department: "Engineering",
    position: "Project Manager",
    avatar: "",
    joinDate: "2023-01-15",
    status: "active",
    skills: ["Project Management", "Agile", "Leadership"],
    projects: ["1", "2"],
    performance: {
      completedTasks: 45,
      totalTasks: 50,
      rating: 4.8,
    },
  },
  {
    _id: "2",
    firstName: "Mike",
    lastName: "Chen",
    email: "mike@example.com",
    phone: "+1-555-0102",
    role: "member",
    department: "Engineering",
    position: "Senior Developer",
    avatar: "",
    joinDate: "2023-03-20",
    status: "active",
    skills: ["React", "Node.js", "TypeScript"],
    projects: ["1", "3"],
    performance: {
      completedTasks: 38,
      totalTasks: 42,
      rating: 4.6,
    },
  },
  {
    _id: "3",
    firstName: "Emily",
    lastName: "Davis",
    email: "emily@example.com",
    phone: "+1-555-0103",
    role: "member",
    department: "Design",
    position: "UI/UX Designer",
    avatar: "",
    joinDate: "2023-02-10",
    status: "active",
    skills: ["Figma", "Adobe Creative Suite", "User Research"],
    projects: ["2", "4"],
    performance: {
      completedTasks: 32,
      totalTasks: 35,
      rating: 4.9,
    },
  },
];

export const mockNotifications = [
  {
    _id: "1",
    type: "task_assigned",
    title: "New task assigned",
    message: "You have been assigned to 'Update user interface'",
    read: false,
    user: "1",
    actionUrl: "/tasks/1",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    _id: "2",
    type: "deadline_approaching",
    title: "Project deadline approaching",
    message: "'Mobile App Redesign' is due in 2 days",
    read: false,
    user: "1",
    actionUrl: "/projects/2",
    createdAt: "2024-01-15T09:15:00Z",
  },
  {
    _id: "3",
    type: "budget_alert",
    title: "Budget alert",
    message: "Project 'E-commerce Platform' has exceeded 80% of budget",
    read: true,
    user: "1",
    actionUrl: "/budget",
    createdAt: "2024-01-14T16:20:00Z",
  },
];